In [23]:
import joblib
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")

In [24]:
df = pd.read_csv("espectativa_vida.csv")

In [25]:
novo_df = pd.DataFrame({'country': df['Country'],
                       'life_expectancy': df['Life expectancy '],
                       'year': df['Year'],
                       'status': df['Status'],
                       'adult_mortality': df['Adult Mortality'],
                       'inf_death': df['infant deaths'],
                       'alcohol': df['Alcohol'],
                       'hepatitisB': df['Hepatitis B'],
                       'measles': df['Measles '],
                       'bmi': df[' BMI '],
                       'polio': df['Polio'],
                       'diphtheria': df['Diphtheria '],
                       'hiv': df[' HIV/AIDS'],
                       'gdp': df['GDP'],
                       'total_expenditure': df['Total expenditure'],
                       'thinness_till19': df[' thinness  1-19 years'],
                       'thinness_till9': df[' thinness 5-9 years'],
                       'school': df['Schooling'],
                       'population': df[' Population']})

In [26]:
"""
def process_data(data, years, country, selected_columns):
    # Filtrar os dados pelos anos e pelo país especificado
    filtered_data = data[(data['Year'].isin(years)) & (data['Country'] == country)]
    
    # Calcular as médias apenas para as colunas selecionadas
    means = filtered_data[selected_columns].mean()
    
    # Substituir os valores apenas nas colunas selecionadas pelas médias
    for column in selected_columns:
        filtered_data[column] = means[column]
    
    return filtered_data
"""
def process_data(data, years, country):
    # Filtrar os dados pelos anos e pelo país especificado
    filtered_data = data[(data['year'].isin(years)) & (data['country'] == country)]
    
    # Selecionar as colunas numéricas, excluindo "Year"
    numeric_columns = filtered_data.select_dtypes(include='number').columns
    numeric_columns = [col for col in numeric_columns if col != 'year']
    
    # Calcular as médias para as colunas selecionadas
    means = filtered_data[numeric_columns].mean()
    
    # Substituir os valores nas colunas selecionadas pelas médias
    for column in numeric_columns:
        filtered_data[column] = means[column]
    
    return filtered_data


### verificar para pular o indice a cada tres linhas e calcular a media dos proximos tres.
### ou verificar, onde os anos forem iguais a 2000, 2001 e 2002, ele calcula a media e
### e coloca nas variaveis numericas, depois ele faz o mesmo passo para as proximas tres linhas e anos etc

In [27]:
novo_df

,country,life_expectancy,year,status,adult_mortality,inf_death,alcohol,hepatitisB,measles,bmi,polio,diphtheria,hiv,gdp,total_expenditure,thinness_till19,thinness_till9,school,population
0,Afghanistan,65.0,2015,Developing,263.0,62,0.01,65.0,1154,19.1,6.0,65.0,0.1,584.259210,8.16,17.2,17.3,10.1,33736494.0
1,Afghanistan,59.9,2014,Developing,271.0,64,0.01,62.0,492,18.6,58.0,62.0,0.1,612.696514,8.18,17.5,17.5,10.0,327582.0
2,Afghanistan,59.9,2013,Developing,268.0,66,0.01,64.0,430,18.1,62.0,64.0,0.1,631.744976,8.13,17.7,17.7,9.9,31731688.0
3,Afghanistan,59.5,2012,Developing,272.0,69,0.01,67.0,2787,17.6,67.0,67.0,0.1,669.959000,8.52,17.9,18.0,9.8,3696958.0
4,Afghanistan,59.2,2011,Developing,275.0,71,0.01,68.0,3013,17.2,68.0,68.0,0.1,63.537231,7.87,18.2,18.2,9.5,2978599.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,44.3,2004,Developing,723.0,27,4.36,68.0,31,27.1,67.0,65.0,33.6,454.366654,7.13,9.4,9.4,9.2,12777511.0
2934,Zimbabwe,44.5,2003,Developing,715.0,26,4.06,7.0,998,26.7,7.0,68.0,36.7,453.351155,6.52,9.8,9.9,9.5,12633897.0
2935,Zimbabwe,44.8,2002,Developing,73.0,25,4.43,73.0,304,26.3,73.0,71.0,39.8,57.348340,6.53,1.2,1.3,10.0,125525.0
2936,Zimbabwe,45.3,2001,Developing,686.0,25,1.72,76.0,529,25.9,76.0,75.0,42.1,548.587312,6.16,1.6,1.7,9.8,12366165.0
2937,Zimbabwe,46.0,2000,Developing,665.0,24,1.68,79.0,1483,25.5,78.0,78.0,43.5,547.358878,7.10,11.0,11.2,9.8,12222251.0

In [28]:
# Exemplo de uso:
# Criando um DataFrame de exemplo
data = novo_df

# Anos e País para filtrar
years = [2000, 2001, 2002]
country = 'Brazil'

# colunas que serao imputadas as medias
# selected_columns = []

# Processar os dados
# processed_data = process_data(data, years, country, selected_columns)
processed_data = process_data(data, years, country)
print(processed_data)

    country  life_expectancy  year      status  adult_mortality  inf_death  \
365  Brazil        72.466667  2002  Developing       179.333333      103.0
366  Brazil        72.466667  2001  Developing       179.333333      103.0
367  Brazil        72.466667  2000  Developing       179.333333      103.0

     alcohol  hepatitisB    measles   bmi  polio  diphtheria  hiv         gdp  \
365     7.13   92.333333  12.666667  44.5   99.0   98.333333  0.1  3235.24022
366     7.13   92.333333  12.666667  44.5   99.0   98.333333  0.1  3235.24022
367     7.13   92.333333  12.666667  44.5   99.0   98.333333  0.1  3235.24022

     total_expenditure  thinness_till19  thinness_till9     school  \
365           7.206667         3.366667        3.366667  14.333333
366           7.206667         3.366667        3.366667  14.333333
367           7.206667         3.366667        3.366667  14.333333

       population
365  5.962676e+07
366  5.962676e+07
367  5.962676e+07

In [30]:
processed_data

,country,life_expectancy,year,status,adult_mortality,inf_death,alcohol,hepatitisB,measles,bmi,polio,diphtheria,hiv,gdp,total_expenditure,thinness_till19,thinness_till9,school,population
365,Brazil,72.466667,2002,Developing,179.333333,103.0,7.13,92.333333,12.666667,44.5,99.0,98.333333,0.1,3235.24022,7.206667,3.366667,3.366667,14.333333,5.962676e+07
366,Brazil,72.466667,2001,Developing,179.333333,103.0,7.13,92.333333,12.666667,44.5,99.0,98.333333,0.1,3235.24022,7.206667,3.366667,3.366667,14.333333,5.962676e+07
367,Brazil,72.466667,2000,Developing,179.333333,103.0,7.13,92.333333,12.666667,44.5,99.0,98.333333,0.1,3235.24022,7.206667,3.366667,3.366667,14.333333,5.962676e+07

In [29]:
#df_2014 = df[novo_df['year'].astype(str) == '2014']
#df_2014.to_csv('dados_2014.csv', index=False)
#df = pd.read_csv("dados_2014.csv")
df_filtrado = df[novo_df['year'].isin([2000, 2001, 2002])]

In [21]:
df_filtrado

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
13,Afghanistan,2002,Developing,56.2,3.0,88,0.01,16.887351,64.0,2486,...,36.0,7.76,36.0,0.1,187.845950,21979923.0,19.9,2.2,0.341,6.2
14,Afghanistan,2001,Developing,55.3,316.0,88,0.01,10.574728,63.0,8762,...,35.0,7.80,33.0,0.1,117.496980,2966463.0,2.1,2.4,0.340,5.9
15,Afghanistan,2000,Developing,54.8,321.0,88,0.01,10.424960,62.0,6532,...,24.0,8.20,24.0,0.1,114.560000,293756.0,2.3,2.5,0.338,5.5
29,Albania,2002,Developing,73.3,15.0,1,3.73,104.516916,96.0,16,...,98.0,6.30,98.0,0.1,1453.642777,3511.0,2.0,2.1,0.670,10.7
30,Albania,2001,Developing,73.6,14.0,1,4.25,96.205571,96.0,18,...,97.0,6.00,97.0,0.1,1326.973390,36173.0,2.1,2.1,0.662,10.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,Zambia,2001,Developing,44.6,611.0,43,2.61,46.830275,NaN,16997,...,86.0,6.56,85.0,18.6,378.273624,1824125.0,7.4,7.4,0.424,9.8
2921,Zambia,2000,Developing,43.8,614.0,44,2.62,45.616880,NaN,30930,...,85.0,7.16,85.0,18.7,341.955625,1531221.0,7.5,7.5,0.418,9.6
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [22]:
df.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
 Population                        float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object